### PR TITLE
reformatting api_build

### PR DESCRIPTION
**Pull request by macdiesel**
@efagin PTAL.

### CODE REVIEW

**Comment by doctoryes** [comment]
*That's* how we like it! Definitely more readable. 👍 

@efagin It's up to you whether you'd want to run this again as a test before we merge.

**Comment by macdiesel** [comment]
lol I would! ;)

**Comment by macdiesel** [comment]
I've completed my final pass on this.

**Comment by efagin** [comment]
👍 merging. thanks! you're a better engineer than that `reverse_engineer` guy ever will be, @macdiesel.

**Pull request merged**
